package net.bandithemepark.bandicore.network.audioserver.map

import net.kyori.adventure.text.Component
import org.bukkit.Bukkit
import org.bukkit.Material
import org.bukkit.block.Block
import org.bukkit.block.data.type.TrapDoor

enum class MaterialTextures(val texture: String, val transparent: Boolean = false) {
    // All full blocks only. If a block is not in here, it should not be rendered. If a block is transparent, the next non-transparent block under it should be rendered first
    ACACIA_LEAVES("acacia_leaves", true),
    ACACIA_LOG("acacia_log_top"),
    ACACIA_PLANKS("acacia_planks"),
    ACACIA_SLAB("acacia_planks"),
    ACACIA_STAIRS("acacia_planks"),
    ACACIA_WOOD("acacia_log"),
    AMETHYST_BLOCK("amethyst_block"),
    ANCIENT_DEBRIS("ancient_debris_top"),
    ANDESITE("andesite"),
    ANDESITE_SLAB("andesite"),
    ANDESITE_STAIRS("andesite"),
    AZALEA("azalea_top"),
    AZALEA_LEAVES("azalea_leaves", true),
    BARREL("barrel_top"),
    BASALT("basalt_top"),
    BEACON("beacon", true),
    BEDROCK("bedrock"),
    BEE_NEST("bee_nest_top"),
    BEEHIVE("beehive_end"),
    BIRCH_LEAVES("birch_leaves", true),
    BIRCH_LOG("birch_log_top"),
    BIRCH_PLANKS("birch_planks"),
    BIRCH_SLAB("birch_planks"),
    BIRCH_STAIRS("birch_planks"),
    BIRCH_WOOD("birch_log"),
    BLACK_CARPET("black_wool"),
    BLACK_CONCRETE("black_concrete"),
    BLACK_CONCRETE_POWDER("black_concrete_powder"),
    BLACK_GLAZED_TERRACOTTA("black_glazed_terracotta"),
    BLACK_SHULKER_BOX("black_shulker_box"),
    BLACK_STAINED_GLASS("black_stained_glass", true),
    BLACK_TERRACOTTA("black_terracotta"),
    BLACK_WOOL("black_wool"),
    BLACKSTONE("blackstone_top"),
    BLACKSTONE_SLAB("blackstone_top"),
    BLACKSTONE_STAIRS("blackstone_top"),
    BLAST_FURNACE("blast_furnace_top"),
    BLUE_CARPET("blue_wool"),
    BLUE_CONCRETE("blue_concrete"),
    BLUE_CONCRETE_POWDER("blue_concrete_powder"),
    BLUE_GLAZED_TERRACOTTA("blue_glazed_terracotta"),
    BLUE_ICE("blue_ice"),
    BLUE_SHULKER_BOX("blue_shulker_box"),
    BLUE_STAINED_GLASS("blue_stained_glass", true),
    BLUE_TERRACOTTA("blue_terracotta"),
    BLUE_WOOL("blue_wool"),
    BONE_BLOCK("bone_block_top"),
    BOOKSHELF("oak_planks"),
    BRAIN_CORAL_BLOCK("brain_coral_block"),
    BRICK_SLAB("bricks"),
    BRICK_STAIRS("bricks"),
    BRICKS("bricks"),
    BROWN_CARPET("brown_wool"),
    BROWN_CONCRETE("brown_concrete"),
    BROWN_CONCRETE_POWDER("brown_concrete_powder"),
    BROWN_GLAZED_TERRACOTTA("brown_glazed_terracotta"),
    BROWN_MUSHROOM_BLOCK("brown_mushroom_block"),
    BROWN_SHULKER_BOX("brown_shulker_box"),
    BROWN_STAINED_GLASS("brown_stained_glass", true),
    BROWN_TERRACOTTA("brown_terracotta"),
    BROWN_WOOL("brown_wool"),
    BUBBLE_CORAL_BLOCK("bubble_coral_block"),
    BUDDING_AMETHYST("budding_amethyst"),
    CALCITE("calcite"),
    CARTOGRAPHY_TABLE("cartography_table_top"),
    CARVED_PUMPKIN("pumpkin_top"),
    CAULDRON("cauldron_inner"),
    CHISELED_DEEPSLATE("chiseled_deepslate"),
    CHISELED_NETHER_BRICKS("chiseled_nether_bricks"),
    CHISELED_POLISHED_BLACKSTONE("chiseled_polished_blackstone"),
    CHISELED_QUARTZ_BLOCK("chiseled_quartz_block"),
    CHISELED_RED_SANDSTONE("red_sandstone_top"),
    CHISELED_SANDSTONE("sandstone_top"),
    CHISELED_STONE_BRICKS("chiseled_stone_bricks"),
    CLAY("clay"),
    COAL_BLOCK("coal_block"),
    COAL_ORE("coal_ore"),
    COARSE_DIRT("coarse_dirt"),
    COBBLED_DEEPSLATE("cobbled_deepslate"),
    COBBLED_DEEPSLATE_SLAB("cobbled_deepslate"),
    COBBLED_DEEPSLATE_STAIRS("cobbled_deepslate"),
    COBBLESTONE("cobblestone"),
    COBBLESTONE_SLAB("cobblestone"),
    COBBLESTONE_STAIRS("cobblestone"),
    COMPARATOR("comparator"),
    COMPOSTER("composter_bottom"),
    COPPER_BLOCK("copper_block"),
    COPPER_ORE("copper_ore"),
    CRACKED_DEEPSLATE_BRICKS("cracked_deepslate_bricks"),
    CRACKED_DEEPSLATE_TILES("cracked_deepslate_tiles"),
    CRACKED_NETHER_BRICKS("cracked_nether_bricks"),
    CRACKED_POLISHED_BLACKSTONE_BRICKS("cracked_polished_blackstone_bricks"),
    CRACKED_STONE_BRICKS("cracked_stone_bricks"),
    CRAFTING_TABLE("crafting_table_top"),
    CRIMSON_HYPHAE("crimson_stem"),
    CRIMSON_NYLIUM("crimson_nylium"),
    CRIMSON_PLANKS("crimson_planks"),
    CRIMSON_SLAB("crimson_planks"),
    CRIMSON_STAIRS("crimson_planks"),
    CRIMSON_STEM("crimson_stem_top"),
    CRYING_OBSIDIAN("crying_obsidian"),
    CUT_COPPER("cut_copper"),
    CUT_COPPER_SLAB("cut_copper"),
    CUT_COPPER_STAIRS("cut_copper"),
    CUT_RED_SANDSTONE("red_sandstone_top"),
    CUT_RED_SANDSTONE_SLAB("red_sandstone_top"),
    CUT_SANDSTONE("sandstone_top"),
    CUT_SANDSTONE_SLAB("sandstone_top"),
    CYAN_CARPET("cyan_wool"),
    CYAN_CONCRETE("cyan_concrete"),
    CYAN_CONCRETE_POWDER("cyan_concrete_powder"),
    CYAN_GLAZED_TERRACOTTA("cyan_glazed_terracotta"),
    CYAN_SHULKER_BOX("cyan_shulker_box"),
    CYAN_STAINED_GLASS("cyan_stained_glass", true),
    CYAN_TERRACOTTA("cyan_terracotta"),
    CYAN_WOOL("cyan_wool"),
    DARK_OAK_LEAVES("dark_oak_leaves", true),
    DARK_OAK_LOG("dark_oak_log_top"),
    DARK_OAK_PLANKS("dark_oak_planks"),
    DARK_OAK_SLAB("dark_oak_planks"),
    DARK_OAK_STAIRS("dark_oak_planks"),
    DARK_OAK_WOOD("dark_oak_log"),
    DARK_PRISMARINE("dark_prismarine"),
    DARK_PRISMARINE_SLAB("dark_prismarine"),
    DARK_PRISMARINE_STAIRS("dark_prismarine"),
    DAYLIGHT_DETECTOR("daylight_detector_top"),
    DEAD_BRAIN_CORAL_BLOCK("dead_brain_coral_block"),
    DEAD_BUBBLE_CORAL_BLOCK("dead_bubble_coral_block"),
    DEAD_FIRE_CORAL_BLOCK("dead_fire_coral_block"),
    DEAD_HORN_CORAL_BLOCK("dead_horn_coral_block"),
    DEAD_TUBE_CORAL_BLOCK("dead_tube_coral_block"),
    DEEPSLATE("deepslate"),
    DEEPSLATE_BRICK_SLAB("deepslate_bricks"),
    DEEPSLATE_BRICK_STAIRS("deepslate_bricks"),
    DEEPSLATE_BRICKS("deepslate_bricks"),
    DEEPSLATE_COAL_ORE("deepslate_coal_ore"),
    DEEPSLATE_COPPER_ORE("deepslate_copper_ore"),
    DEEPSLATE_DIAMOND_ORE("deepslate_diamond_ore"),
    DEEPSLATE_EMERALD_ORE("deepslate_emerald_ore"),
    DEEPSLATE_GOLD_ORE("deepslate_gold_ore"),
    DEEPSLATE_IRON_ORE("deepslate_iron_ore"),
    DEEPSLATE_LAPIS_ORE("deepslate_lapis_ore"),
    DEEPSLATE_REDSTON_ORE("deepslate_redstone_ore"),
    DEEPSLATE_TILE_SLAB("deepslate_tiles"),
    DEEPSLATE_TILE_STAIRS("deepslate_tiles"),
    DEEPSLATE_TILES("deepslate_tiles"),
    DIAMOND_BLOCK("diamond_block"),
    DIAMOND_ORE("diamond_ore"),
    DIORITE("diorite"),
    DIORITE_SLAB("diorite"),
    DIORITE_STAIRS("diorite"),
    DIRT("dirt"),
    DIRT_PATH("dirt_path_top"),
    DISPENSER("furnace_top"),
    DRIED_KELP_BLOCK("dried_kelp_top"),
    DRIPSTONE_BLOCK("dripstone_block"),
    DROPPER("furnace_top"),
    EMERALD_BLOCK("emerald_block"),
    EMERALD_ORE("emerald_ore"),
    END_PORTAL_FRAME("end_portal_frame_top"),
    END_STONE("end_stone"),
    END_STONE_BRICKS("end_stone_bricks"),
    END_STONE_BRICK_SLAB("end_stone_bricks"),
    END_STONE_BRICK_STAIRS("end_stone_bricks"),
    EXPOSED_COPPER("exposed_copper"),
    EXPOSED_CUT_COPPER("exposed_cut_copper"),
    EXPOSED_CUT_COPPER_SLAB("exposed_cut_copper"),
    EXPOSED_CUT_COPPER_STAIRS("exposed_cut_copper"),
    FARMLAND("farmland"),
    FIRE_CORAL_BLOCK("fire_coral_block"),
    FLETCHING_TABLE("fletching_table_top"),
    FLOWERING_AZALEA("flowering_azalea_top"),
    FLOWERING_AZALEA_LEAVES("flowering_azalea_leaves", true),
    FROSTED_ICE("frosted_ice_0"),
    FURNACE("furnace_top"),
    GILDED_BLACKSTONE("gilded_blackstone"),
    GLASS("glass", true),
    GLOWSTONE("glowstone"),
    GOLD_BLOCK("gold_block"),
    GOLD_ORE("gold_ore"),
    GRANITE("granite"),
    GRANITE_SLAB("granite"),
    GRANITE_STAIRS("granite"),
    GRASS_BLOCK("grass_block_top"),
    GRAVEL("gravel"),
    GRAY_CARPET("gray_wool"),
    GRAY_CONCRETE("gray_concrete"),
    GRAY_CONCRETE_POWDER("gray_concrete_powder"),
    GRAY_GLAZED_TERRACOTTA("gray_glazed_terracotta"),
    GRAY_SHULKER_BOX("gray_shulker_box"),
    GRAY_STAINED_GLASS("gray_stained_glass", true),
    GRAY_TERRACOTTA("gray_terracotta"),
    GRAY_WOOL("gray_wool"),
    GREEN_CARPET("green_wool"),
    GREEN_CONCRETE("green_concrete"),
    GREEN_CONCRETE_POWDER("green_concrete_powder"),
    GREEN_GLAZED_TERRACOTTA("green_glazed_terracotta"),
    GREEN_SHULKER_BOX("green_shulker_box"),
    GREEN_STAINED_GLASS("green_stained_glass", true),
    GREEN_TERRACOTTA("green_terracotta"),
    GREEN_WOOL("green_wool"),
    HAY_BLOCK("hay_block_top"),
    HONEY_BLOCK("honey_block_top"),
    HONEYCOMB_BLOCK("honeycomb_block"),
    HOPPER("hopper_inside"),
    HORN_CORAL_BLOCK("horn_coral_block"),
    ICE("ice"),
    INFESTED_CHISELED_STONE_BRICKS("chiseled_stone_bricks"),
    INFESTED_COBBLESTONE("cobblestone"),
    INFESTED_CRACKED_STONE_BRICKS("cracked_stone_bricks"),
    INFESTED_DEEPSLATE("deepslate"),
    INFESTED_MOSSY_STONE_BRICKS("mossy_stone_bricks"),
    INFESTED_STONE("stone"),
    INFESTED_STONE_BRICKS("stone_bricks"),
    IRON_BLOCK("iron_block"),
    IRON_ORE("iron_ore"),
    JUKEBOX("jukebox_top"),
    JUNGLE_LEAVES("jungle_leaves", true),
    JUNGLE_LOG("jungle_log_top"),
    JUNGLE_PLANKS("jungle_planks"),
    JUNGLE_SLAB("jungle_planks"),
    JUNGLE_STAIRS("jungle_planks"),
    JUNGLE_WOOD("jungle_log"),
    LAPIS_BLOCK("lapis_block"),
    LAPIS_ORE("lapis_ore"),
    LAVA("lava_still"),
    LECTERN("lectern_base"),
    LIGHT_BLUE_CARPET("light_blue_wool"),
    LIGHT_BLUE_CONCRETE("light_blue_concrete"),
    LIGHT_BLUE_CONCRETE_POWDER("light_blue_concrete_powder"),
    LIGHT_BLUE_GLAZED_TERRACOTTA("light_blue_glazed_terracotta"),
    LIGHT_BLUE_SHULKER_BOX("light_blue_shulker_box"),
    LIGHT_BLUE_STAINED_GLASS("light_blue_stained_glass", true),
    LIGHT_BLUE_TERRACOTTA("light_blue_terracotta"),
    LIGHT_BLUE_WOOL("light_blue_wool"),
    LIGHT_GRAY_CARPET("light_gray_wool"),
    LIGHT_GRAY_CONCRETE("light_gray_concrete"),
    LIGHT_GRAY_CONCRETE_POWDER("light_gray_concrete_powder"),
    LIGHT_GRAY_GLAZED_TERRACOTTA("light_gray_glazed_terracotta"),
    LIGHT_GRAY_SHULKER_BOX("light_gray_shulker_box"),
    LIGHT_GRAY_STAINED_GLASS("light_gray_stained_glass", true),
    LIGHT_GRAY_TERRACOTTA("light_gray_terracotta"),
    LIGHT_GRAY_WOOL("light_gray_wool"),
    LILY_PAD("lily_pad", true),
    LIME_CARPET("lime_wool"),
    LIME_CONCRETE("lime_concrete"),
    LIME_CONCRETE_POWDER("lime_concrete_powder"),
    LIME_GLAZED_TERRACOTTA("lime_glazed_terracotta"),
    LIME_SHULKER_BOX("lime_shulker_box"),
    LIME_STAINED_GLASS("lime_stained_glass", true),
    LIME_TERRACOTTA("lime_terracotta"),
    LIME_WOOL("lime_wool"),
    LODESTONE("lodestone_top"),
    LOOM("loom_top"),
    MAGENTA_CARPET("magenta_wool"),
    MAGENTA_CONCRETE("magenta_concrete"),
    MAGENTA_CONCRETE_POWDER("magenta_concrete_powder"),
    MAGENTA_GLAZED_TERRACOTTA("magenta_glazed_terracotta"),
    MAGENTA_SHULKER_BOX("magenta_shulker_box"),
    MAGENTA_STAINED_GLASS("magenta_stained_glass", true),
    MAGENTA_TERRACOTTA("magenta_terracotta"),
    MAGENTA_WOOL("magenta_wool"),
    MAGMA_BLOCK("magma"),
    MELON("melon_top"),
    MOSS_BLOCK("moss_block"),
    MOSS_CARPET("moss_block"),
    MOSSY_COBBLESTONE("mossy_cobblestone"),
    MOSSY_COBBLESTONE_SLAB("mossy_cobblestone"),
    MOSSY_COBBLESTONE_STAIRS("mossy_cobblestone"),
    MOSSY_STONE_BRICKS("mossy_stone_bricks"),
    MOSSY_STONE_BRICK_SLAB("mossy_stone_bricks"),
    MOSSY_STONE_BRICK_STAIRS("mossy_stone_bricks"),
    MUSHROOM_STEM("mushroom_stem"),
    MYCELIUM("mycelium_top"),
    NETHER_BRICK_SLAB("nether_bricks"),
    NETHER_BRICK_STAIRS("nether_bricks"),
    NETHER_BRICKS("nether_bricks"),
    NETHER_GOLD_ORE("nether_gold_ore"),
    NETHER_QUARTZ_ORE("nether_quartz_ore"),
    NETHER_WART_BLOCK("nether_wart_block"),
    NETHERITE_BLOCK("netherite_block"),
    NETHERRACK("netherrack"),
    NOTE_BLOCK("note_block"),
    OAK_LEAVES("oak_leaves", true),
    OAK_LOG("oak_log_top"),
    OAK_PLANKS("oak_planks"),
    OAK_SLAB("oak_planks"),
    OAK_STAIRS("oak_planks"),
    OAK_WOOD("oak_log"),
    OBSERVER("observer_top"),
    OBSIDIAN("obsidian"),
    ORANGE_CARPET("orange_wool"),
    ORANGE_CONCRETE("orange_concrete"),
    ORANGE_CONCRETE_POWDER("orange_concrete_powder"),
    ORANGE_GLAZED_TERRACOTTA("orange_glazed_terracotta"),
    ORANGE_SHULKER_BOX("orange_shulker_box"),
    ORANGE_STAINED_GLASS("orange_stained_glass", true),
    ORANGE_TERRACOTTA("orange_terracotta"),
    ORANGE_WOOL("orange_wool"),
    OXIDIZED_COPPER("oxidized_copper"),
    OXIDIZED_CUT_COPPER("oxidized_cut_copper"),
    OXIDIZED_CUT_COPPER_SLAB("oxidized_cut_copper"),
    OXIDIZED_CUT_COPPER_STAIRS("oxidized_cut_copper"),
    PACKED_ICE("packed_ice"),
    PETRIFIED_OAK_SLAB("oak_planks"),
    PINK_CARPET("pink_wool"),
    PINK_CONCRETE("pink_concrete"),
    PINK_CONCRETE_POWDER("pink_concrete_powder"),
    PINK_GLAZED_TERRACOTTA("pink_glazed_terracotta"),
    PINK_SHULKER_BOX("pink_shulker_box"),
    PINK_STAINED_GLASS("pink_stained_glass", true),
    PINK_TERRACOTTA("pink_terracotta"),
    PINK_WOOL("pink_wool"),
    PISTON("piston_top"),
    PODZOL("podzol_top"),
    POLISHED_ANDESITE("polished_andesite"),
    POLISHED_ANDESITE_SLAB("polished_andesite"),
    POLISHED_ANDESITE_STAIRS("polished_andesite"),
    POLISHED_BASALT("polished_basalt_top"),
    POLISHED_BLACKSTONE("polished_blackstone"),
    POLISHED_BLACKSTONE_BRICKS("polished_blackstone_bricks"),
    POLISHED_BLACKSTONE_BRICK_SLAB("polished_blackstone_bricks"),
    POLISHED_BLACKSTONE_BRICK_STAIRS("polished_blackstone_bricks"),
    POLISHED_BLACKSTONE_SLAB("polished_blackstone"),
    POLISHED_BLACKSTONE_STAIRS("polished_blackstone"),
    POLISHED_DEEPSLATE("polished_deepslate"),
    POLISHED_DEEPSLATE_SLAB("polished_deepslate"),
    POLISHED_DEEPSLATE_STAIRS("polished_deepslate"),
    POLISHED_DIORITE("polished_diorite"),
    POLISHED_DIORITE_SLAB("polished_diorite"),
    POLISHED_DIORITE_STAIRS("polished_diorite"),
    POLISHED_GRANITE("polished_granite"),
    POLISHED_GRANITE_SLAB("polished_granite"),
    POLISHED_GRANITE_STAIRS("polished_granite"),
    POWDER_SNOW("powder_snow"),
    PRISMARINE("prismarine"),
    PRISMARINE_BRICKS("prismarine_bricks"),
    PRISMARINE_BRICK_SLAB("prismarine_bricks"),
    PRISMARINE_BRICK_STAIRS("prismarine_bricks"),
    PRISMARINE_SLAB("prismarine"),
    PRISMARINE_STAIRS("prismarine"),
    PUMPKIN("pumpkin_top"),
    PURPLE_CARPET("purple_wool"),
    PURPLE_CONCRETE("purple_concrete"),
    PURPLE_CONCRETE_POWDER("purple_concrete_powder"),
    PURPLE_GLAZED_TERRACOTTA("purple_glazed_terracotta"),
    PURPLE_SHULKER_BOX("purple_shulker_box"),
    PURPLE_STAINED_GLASS("purple_stained_glass", true),
    PURPLE_TERRACOTTA("purple_terracotta"),
    PURPLE_WOOL("purple_wool"),
    PURPUR_BLOCK("purpur_block"),
    PURPUR_PILLAR("purpur_pillar_top"),
    PURPUR_SLAB("purpur_block"),
    PURPUR_STAIRS("purpur_block"),
    QUARTZ_BLOCK("quartz_block_top"),
    QUARTZ_BRICKS("quartz_bricks"),
    QUARTZ_PILLAR("quartz_pillar_top"),
    QUARTZ_SLAB("quartz_block_top"),
    QUARTZ_STAIRS("quartz_block_top"),
    RAW_COPPER_BLOCK("raw_copper_block"),
    RAW_GOLD_BLOCK("raw_gold_block"),
    RAW_IRON_BLOCK("raw_iron_block"),
    RED_CARPET("red_wool"),
    RED_CONCRETE("red_concrete"),
    RED_CONCRETE_POWDER("red_concrete_powder"),
    RED_GLAZED_TERRACOTTA("red_glazed_terracotta"),
    RED_MUSHROOM_BLOCK("red_mushroom_block"),
    RED_NETHER_BRICKS("red_nether_bricks"),
    RED_NETHER_BRICK_SLAB("red_nether_bricks"),
    RED_NETHER_BRICK_STAIRS("red_nether_bricks"),
    RED_SAND("red_sand"),
    RED_SANDSTONE("red_sandstone_top"),
    RED_SANDSTONE_SLAB("red_sandstone_top"),
    RED_SANDSTONE_STAIRS("red_sandstone_top"),
    RED_SHULKER_BOX("red_shulker_box"),
    RED_STAINED_GLASS("red_stained_glass", true),
    RED_TERRACOTTA("red_terracotta"),
    RED_WOOL("red_wool"),
    REDSTONE_BLOCK("redstone_block"),
    REDSTONE_ORE("redstone_ore"),
    REPEATER("repeater"),
    RESPAWN_ANCHOR("respawn_anchor_top_off"),
    ROOTED_DIRT("rooted_dirt"),
    SAND("sand"),
    SANDSTONE("sandstone_top"),
    SANDSTONE_SLAB("sandstone_top"),
    SANDSTONE_STAIRS("sandstone_top"),
    SCAFFOLDING("scaffolding_top", true),
    SEA_LANTERN("sea_lantern"),
    SHROOMLIGHT("shroomlight"),
    SHULKER_BOX("shulker_box"),
    SLIME_BLOCK("slime_block"),
    SMITHING_TABLE("smithing_table_top"),
    SMOKER("smoker_top"),
    SMOOTH_BASALT("smooth_basalt"),
    SMOOTH_QUARTZ("quartz_block_bottom"),
    SMOOTH_QUARTZ_SLAB("quartz_block_bottom"),
    SMOOTH_QUARTZ_STAIRS("quartz_block_bottom"),
    SMOOTH_RED_SANDSTONE("red_sandstone_top"),
    SMOOTH_RED_SANDSTONE_SLAB("red_sandstone_top"),
    SMOOTH_RED_SANDSTONE_STAIRS("red_sandstone_top"),
    SMOOTH_SANDSTONE("sandstone_top"),
    SMOOTH_SANDSTONE_SLAB("sandstone_top"),
    SMOOTH_SANDSTONE_STAIRS("sandstone_top"),
    SMOOTH_STONE("smooth_stone"),
    SMOOTH_STONE_SLAB("smooth_stone"),
    SNOW_BLOCK("snow"),
    SPAWNER("spawner", true),
    SPONGE("sponge"),
    SPRUCE_LEAVES("spruce_leaves", true),
    SPRUCE_LOG("spruce_log_top"),
    SPRUCE_PLANKS("spruce_planks"),
    SPRUCE_SLAB("spruce_planks"),
    SPRUCE_STAIRS("spruce_planks"),
    SPRUCE_WOOD("spruce_log"),
    STONE("stone"),
    STONE_BRICKS("stone_bricks"),
    STONE_BRICK_SLAB("stone_bricks"),
    STONE_BRICK_STAIRS("stone_bricks"),
    STONE_SLAB("stone"),
    STONE_STAIRS("stone"),
    STONECUTTER("stonecutter_top"),
    STRIPPED_ACACIA_LOG("stripped_acacia_log_top"),
    STRIPPED_ACACIA_WOOD("stripped_acacia_log"),
    STRIPPED_BIRCH_LOG("stripped_birch_log_top"),
    STRIPPED_BIRCH_WOOD("stripped_birch_log"),
    STRIPPED_CRIMSON_HYPHAE("stripped_crimson_stem"),
    STRIPPED_CRIMSON_STEM("stripped_crimson_stem_top"),
    STRIPPED_DARK_OAK_LOG("stripped_dark_oak_log_top"),
    STRIPPED_DARK_OAK_WOOD("stripped_dark_oak_log"),
    STRIPPED_JUNGLE_LOG("stripped_jungle_log_top"),
    STRIPPED_JUNGLE_WOOD("stripped_jungle_log"),
    STRIPPED_OAK_LOG("stripped_oak_log_top"),
    STRIPPED_OAK_WOOD("stripped_oak_log"),
    STRIPPED_SPRUCE_LOG("stripped_spruce_log_top"),
    STRIPPED_SPRUCE_WOOD("stripped_spruce_log"),
    STRIPPED_WARPED_HYPHAE("stripped_warped_stem"),
    STRIPPED_WARPED_STEM("stripped_warped_stem_top"),
    STRUCTURE_BLOCK("structure_block"),
    TARGET("target_top"),
    TERRACOTTA("terracotta"),
    TINTED_GLASS("tinted_glass", true),
    TNT("tnt_top"),
    TUBE_CORAL_BLOCK("tube_coral_block"),
    TUFF("tuff"),
    WARPED_HYPHAE("warped_stem"),
    WARPED_NYLIUM("warped_nylium"),
    WARPED_PLANKS("warped_planks"),
    WARPED_SLAB("warped_planks"),
    WARPED_STAIRS("warped_planks"),
    WARPED_STEM("warped_stem_top"),
    WAXED_COPPER_BLOCK("copper_block"),
    WAXED_CUT_COPPER("cut_copper"),
    WAXED_CUT_COPPER_SLAB("cut_copper"),
    WAXED_CUT_COPPER_STAIRS("cut_copper"),
    WAXED_EXPOSED_COPPER("exposed_copper"),
    WAXED_EXPOSED_CUT_COPPER("exposed_cut_copper"),
    WAXED_EXPOSED_CUT_COPPER_SLAB("exposed_cut_copper"),
    WAXED_EXPOSED_CUT_COPPER_STAIRS("exposed_cut_copper"),
    WAXED_OXIDIZED_COPPER("oxidized_copper"),
    WAXED_OXIDIZED_CUT_COPPER("oxidized_cut_copper"),
    WAXED_OXIDIZED_CUT_COPPER_SLAB("oxidized_cut_copper"),
    WAXED_OXIDIZED_CUT_COPPER_STAIRS("oxidized_cut_copper"),
    WAXED_WEATHERED_COPPER("weathered_copper"),
    WAXED_WEATHERED_CUT_COPPER("weathered_cut_copper"),
    WAXED_WEATHERED_CUT_COPPER_SLAB("weathered_cut_copper"),
    WAXED_WEATHERED_CUT_COPPER_STAIRS("weathered_cut_copper"),
    WEATHERED_COPPER("weathered_copper"),
    WEATHERED_CUT_COPPER("weathered_cut_copper"),
    WEATHERED_CUT_COPPER_SLAB("weathered_cut_copper"),
    WEATHERED_CUT_COPPER_STAIRS("weathered_cut_copper"),
    WET_SPONGE("wet_sponge"),
    WHITE_CARPET("white_wool"),
    WHITE_CONCRETE("white_concrete"),
    WHITE_CONCRETE_POWDER("white_concrete_powder"),
    WHITE_GLAZED_TERRACOTTA("white_glazed_terracotta"),
    WHITE_SHULKER_BOX("white_shulker_box"),
    WHITE_STAINED_GLASS("white_stained_glass", true),
    WHITE_TERRACOTTA("white_terracotta"),
    WHITE_WOOL("white_wool"),
    YELLOW_CARPET("yellow_wool"),
    YELLOW_CONCRETE("yellow_concrete"),
    YELLOW_CONCRETE_POWDER("yellow_concrete_powder"),
    YELLOW_GLAZED_TERRACOTTA("yellow_glazed_terracotta"),
    YELLOW_SHULKER_BOX("yellow_shulker_box"),
    YELLOW_STAINED_GLASS("yellow_stained_glass", true),
    YELLOW_TERRACOTTA("yellow_terracotta"),
    YELLOW_WOOL("yellow_wool"),
    ACACIA_TRAPDOOR("acacia_trapdoor"),
    BIRCH_TRAPDOOR("birch_trapdoor"),
    CRIMSON_TRAPDOOR("crimson_trapdoor"),
    DARK_OAK_TRAPDOOR("dark_oak_trapdoor"),
    IRON_TRAPDOOR("iron_trapdoor"),
    JUNGLE_TRAPDOOR("jungle_trapdoor"),
    OAK_TRAPDOOR("oak_trapdoor"),
    SPRUCE_TRAPDOOR("spruce_trapdoor"),
    WARPED_TRAPDOOR("warped_trapdoor");

    companion object {
        fun convertBukkit(material: Material): MaterialTextures? {
            return values().find { it.toString() == material.toString() }
        }

        fun convertBukkitSafe(block: Block): MaterialTextures? {
            if(block.type.toString().endsWith("_TRAPDOOR")) {
                val trapdoor = block.blockData as TrapDoor

                return if(trapdoor.isOpen) {
                    null
                } else {
                    values().find { it.toString() == block.type.toString() }
                }
            }

            return values().find { it.toString() == block.type.toString() }
        }
    }
}