name: BandiCore
version: '${version}'
main: net.bandithemepark.bandicore.BandiCore
api-version: 1.18
depend:
  - ProtocolLib
commands:
  servermode:
    description: Change the server mode
  npctest:
    description: Test command for npcs
  ast:
    description: Armorstand editor
    aliases:
      - astools
      - armorstandtools
      - asedit
      - ase
  customplayertest:
    description: Test command for custom players
  painter:
    description: Painter GUI for painting leather items
    aliases:
      - paint
      - paintgui
      - bandicolor
      - color
  track:
    description: All commands related to TrackCoasters
    aliases:
      - trck
      - tracks
      - trcks
      - tr
  trackvehicle:
    description: All commands related to TrackCoasters vehicles
    aliases:
      - trckvehicle
      - tracksvehicle
      - trcksvehicle
      - trv
  gamemode:
    description: Command to players gamemode
    aliases:
      - gm
  setlanguage:
    description: Command to set your preferred language
    aliases:
      - lang
      - language
      - setlang
  setrank:
    description: Set the rank of a player
  bandirestart:
    description: Restart the server using our custom system
  vanish:
    description: Hides the player from any other players