name: BandiCore
version: '${version}'
main: net.bandithemepark.bandicore.BandiCore
api-version: 1.18
depend:
  - ProtocolLib
  - WorldEdit
commands:
  servermode:
    description: Change the server mode
  npctest:
    description: Test command for npcs
  ast:
    description: Armorstand editor
    aliases:
      - astools
      - armorstandtools
      - asedit
      - ase
  customplayertest:
    description: Test command for custom players
  painter:
    description: Painter GUI for painting leather items
    aliases:
      - paint
      - paintgui
      - bandicolor
      - color
  track:
    description: All commands related to TrackCoasters
    aliases:
      - trck
      - tracks
      - trcks
      - tr
  trackvehicle:
    description: All commands related to TrackCoasters vehicles
    aliases:
      - trckvehicle
      - tracksvehicle
      - trcksvehicle
      - trv
  gamemode:
    description: Command to players gamemode
    aliases:
      - gm
  setlanguage:
    description: Command to set your preferred language
    aliases:
      - lang
      - language
      - setlang
  setrank:
    description: Set the rank of a player
  bandirestart:
    description: Restart the server using our custom system
  vanish:
    description: Hides the player from any other players
  queue:
    description: Teleports you to the queue server
  customplayereditor:
    description: Edit custom players and their poses
    aliases: cpe
  bandikea:
    aliases:
      - ikea
      - customblock
  loadworld:
    description: Load a world
  unloadworld:
    description: Unload a world
  worldtp:
    description: Teleport to a world
  teleport:
    aliases:
      - tp
  back:
    description: Travel back to your latest location from your last teleport
  rideoptest:
    description: Testing the rideop menu
  self:
    description: Teleport someone else to yourself
    aliases:
      - s
  night:
    description: Change time of world you are in to night
  day:
    description: Change time of world you are in to day
    aliases:
      - sun
  region:
    description: Everything related to managing regions
    aliases: rg
  rideop:
    description: Operate attractions around the park
  attraction:
    description: Command used for managing and viewing attractions
  chunkrenderer:
    description: Renders the chunk you are currently in